---
- name: Create the k0s bin directory.
  ansible.builtin.file:
    path: "{{ k0s_bin_dir }}"
    state: directory
    mode: "0755"

- name: Create the k0s configuration directory.
  ansible.builtin.file:
    path: "{{ k0s_config_dir }}"
    state: directory
    mode: "0755"

- name: Create the k0s data directory.
  ansible.builtin.file:
    path: "{{ k0s_data_dir }}"
    state: directory
    mode: "0755"

- name: Download the k0s binary.
  ansible.builtin.get_url:
    url: "{{ k0s_download_base }}/{{ k0s_version }}/k0s-{{
      k0s_version }}-{{ k0s_machine_mapping[ansible_architecture] }}"
    dest: "{{ k0s_bin_dir }}/k0s"
    mode: "0755"

- name: Create the k0s configuration file on controller nodes.
  ansible.builtin.template:
    src: k0s.yaml.j2
    dest: "{{ k0s_config_dir }}/{{ k0s_config_file }}"
    mode: "0644"
  when: k0s_control_group in group_names

- name: Configure the k0s genesis node.
  ansible.builtin.include_tasks:
    file: genesis.yml
  when: k0s_genesis_group in group_names

- name: Check if the 'pki' directory exists, which means k0s is already configured.
  ansible.builtin.stat:
    path: "{{ k0s_data_dir }}/pki"
  register: k0s_pki_data_dir

- name: Configure k0s node.
  ansible.builtin.include_tasks:
    file: node.yml
  when: not k0s_pki_data_dir.stat.exists
