---
# vars file for k0s

# Values set here are primarily composed from other default variables and
# potentially set to empty strings.
# These are then used in places like the service template to keep it cleaner.

k0s_genesis_node: "{{ groups[k0s_genesis_group] | intersect(ansible_play_batch) | first }}"

k0s_machine_mapping:
  amd64: amd64
  x86_64: amd64
  arm64: arm64
  aarch64: arm64
  arm: arm
  armv7l: arm
  armv8l: arm

k0s_node_type: "{{ 'controller' if k0s_control_group in group_names else 'worker' }}"

k0s_install:
  - "{{ k0s_bin_dir }}/k0s"
  - install
  - "{{ k0s_node_type }}"

k0s_install_token_file:
  - --token-file
  - "{{ k0s_config_dir }}/k0s.token"
